/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/sctce.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sctce.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ground.geometry} material={materials.ground} position={[0, 0.004, 0]} rotation={[Math.PI, -0.609, Math.PI]}>
        <group position={[-0.051, 0.001, -0.031]}>
          <mesh geometry={nodes.Plane007.geometry} material={materials.buildings} />
          <mesh geometry={nodes.Plane007_1.geometry} material={materials.roofs} />
          <mesh geometry={nodes.Plane007_2.geometry} material={materials['window glass']} />
        </group>
        <group position={[-0.027, 0.019, -0.008]}>
          <mesh geometry={nodes.Plane006.geometry} material={materials.buildings} />
          <mesh geometry={nodes.Plane006_1.geometry} material={materials.roofs} />
        </group>
        <group position={[0.032, 0.02, 0.04]}>
          <mesh geometry={nodes.Plane013.geometry} material={materials.buildings} />
          <mesh geometry={nodes.Plane013_1.geometry} material={materials.roofs} />
        </group>
        <group position={[0.013, 0.011, -0.054]}>
          <mesh geometry={nodes.Plane003.geometry} material={materials.buildings} />
          <mesh geometry={nodes.Plane003_1.geometry} material={materials.roofs} />
          <group position={[0.009, -0.001, 0.001]}>
            <mesh geometry={nodes.Plane004_1.geometry} material={materials['window frame']} />
            <mesh geometry={nodes.Plane004_2.geometry} material={materials['window glass']} />
          </group>
          <group position={[-0.001, -0.001, -0.003]} rotation={[0, 1.571, 0]}>
            <mesh geometry={nodes.Plane005_1.geometry} material={materials['window frame']} />
            <mesh geometry={nodes.Plane005_2.geometry} material={materials['window glass']} />
          </group>
        </group>
        <mesh geometry={nodes.cultsteps.geometry} material={materials.buildings} position={[-0.004, 0.004, -0.033]} />
        <group position={[0.047, 0.015, -0.013]}>
          <mesh geometry={nodes.Plane012.geometry} material={materials.buildings} />
          <mesh geometry={nodes.Plane012_1.geometry} material={materials.roofs} />
        </group>
        <group position={[0.019, 0.015, -0.004]}>
          <mesh geometry={nodes.Plane010.geometry} material={materials.buildings} />
          <mesh geometry={nodes.Plane010_1.geometry} material={materials.roofs} />
        </group>
        <group position={[-0.033, 0.004, -0.056]}>
          <mesh geometry={nodes.Plane.geometry} material={materials.buildings} />
          <mesh geometry={nodes.Plane_1.geometry} material={materials.roofs} />
          <group position={[0.003, -0.001, 0]}>
            <mesh geometry={nodes.Plane002_1.geometry} material={materials['window frame']} />
            <mesh geometry={nodes.Plane002_2.geometry} material={materials['window glass']} />
          </group>
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/sctce.glb')
